version: '3.8'
services:
  web:
    build: .
    command: uvicorn src.gx.app:app --host 0.0.0.0 --reload
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  postgres_data:
